name: Price Scraper Bot

# Startet den Workflow jeden Tag um 03:00 UTC
on:
  schedule:
    - cron: '0 3 * * *'
  # Erlaubt auch das manuelle Ausführen (für Tests)
  workflow_dispatch:

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Code
        # Holt den aktuellen Code (inkl. scraper.py und prices.json)
        uses: actions/checkout@v4
        with:
          # Braucht vollen Token, um den Commit ausführen zu dürfen
          token: ${{ secrets.GITHUB_TOKEN }} 
          
      - name: 2. Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 3. Install Dependencies
        # Installiert requests und beautifulsoup4
        run: pip install requests beautifulsoup4

      - name: 4. Run Scraper Script
        # Führt Ihr Python-Skript aus
        run: python scraper.py

      - name: 5. Commit & Push changes
        # Spezielles Action-Tool, um die geänderte prices.json zurück zu committen
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '🤖 [Bot] Daily price update via Scraper'
          files: prices.json